version: '3.8'

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: guess-game-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # 游戏应用
  app:
    build: .
    container_name: guess-game-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QWEN_API_KEY=${QWEN_API_KEY}
      - QWEN_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1
      - MAX_CONCURRENT_USERS=100
      - SESSION_TIMEOUT=3600
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/games"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: guess-game-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
