services:
  app:
    build:
      context: ..
      dockerfile: deploy/Containerfile
    image: play:${VERSION:-latest}
    container_name: guess-game-app
    volumes:
      - ../data:/app/data
    ports:
      - "7860:7860"
    env_file:
      - ../.env
    restart: unless-stopped
